### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by neal668** [JiahuiYu/audio_recognition#2]
When build the project, recalling 

g++ -Wall -O3 -Wno-unused-result -Iinclude -o bin/build src/build.cpp src/hash.cpp src/fingerprint.cpp src/wav.cpp -lfftw3
In file included from src/build.cpp:23:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/fstream:174:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__undef_min_max:26:2: warning: : macro max is incompatible with C++.
      #undefing max [-W#warnings]
#warning: macro max is incompatible with C++.  #undefing max
 ^
1 warning generated.

Any Idea solving this problem?

**Comment by JiahuiYu** [comment]
Warnings are fine. The software will work with warning.
